import 'course.dart';

final coursesData = [
  Course(
    courseId: '1',
    imageUrl: 'assets/images/image1.jpeg',
    rating: '4.5',
    isBookmarked: false,
    courseTitle: 'Maîtrise de la Culture du Cacao',
    instructor: 'Dr. Angela Yu',
    price: "XAF 17 000",
    duration: '30hr 30mins',
    sectionsLength: '10 Lessons',
    sectionLaps: sections,
    courseTag: tags[0],
  ),
  Course(
    courseId: '2',
    imageUrl: 'assets/images/image2.jpeg',
    rating: '4.2',
    isBookmarked: true,
    courseTitle: 'Techniques de Transformation du Cacao',
    instructor: 'Chris Croft',
    price: "XAF 14 999",
    duration: '4hr 10mins',
    sectionsLength: '5 Lessons',
    sectionLaps: sections,
    courseTag: tags[1],
  ),
  Course(
    courseId: '3',
    imageUrl: 'assets/images/image3.jpeg',
    rating: '3.9',
    isBookmarked: true,
    courseTitle: 'Stratégies de Marketing pour le Cacao',
    instructor: 'Walker',
    price: "XAF 12 000",
    duration: '4hr 30mins',
    sectionsLength: '5 Lessons',
    sectionLaps: sections,
    courseTag: tags[2],
  ),
  Course(
    courseId: '4',
    imageUrl: 'assets/images/image4.jpeg',
    rating: '4.0',
    isBookmarked: false,
    courseTitle: 'Cacao : De la Ferme à la Table',
    instructor: 'Kyle Pew',
    price: "XAF 12 499",
    duration: '39hr 30mins',
    sectionsLength: '50 Lessons',
    sectionLaps: sections,
    courseTag: tags[3],
  ),
  Course(
    courseId: '5',
    imageUrl: 'assets/images/image5.jpeg',
    rating: '4.2',
    isBookmarked: true,
    courseTitle: 'Savoir-Faire en Chocolaterie : Cacao à Chocolat',
    instructor: 'Walker',
    price: "XAF 20 000",
    duration: '24hr 50mins',
    sectionsLength: '50 Lessons',
    sectionLaps: sections,
    courseTag: tags[4],
  ),
];

List sections = [
  ['Introduction à la culture du cacao', '20 min'],
  ['Techniques de récolte', '4h 40 min'],
  ['Transformation du cacao', '2h 20 min'],
  ['Conclusion et perspectives', '40 min'],
];

List tags = [
  'Semence',
  'Fève',
  'Rendement',
  '50% discount',
  'Populaire',
];
